name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:  

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/Byaidu/PDFMathTranslate.git
          git fetch upstream
      
      - name: 合并上游分支
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
